server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://example.org
          predicates:
            - Path=/foo/{segment}
        - id: account-rest-service
          uri: lb://account-rest-service
          predicates:
            - Path=/accounts/validate/secret/{authenticationId}/{secret},
                    /accounts/email/authenticationId/{email},
                    /accounts/emailmysecret/{authenticationId},
                    /accounts/emailactivationlink/{authenticationId},
                    /accounts/authentications/password,
                    /accounts/{authenticationId}/active/{secret},
                    /accounts/{authenticationId}/{email}
        - id: authentication-rest-service
          uri: lb://authentication-rest-service
          predicates:
            - Path=/authentications/authenticate
        - id: user-rest-service
          uri: lb://user-rest-service
          predicates:
            - Path=/users, /users/{authenticationId}, /users/names/{firstName}/{lastName}
        - id: email-rest-service
          uri: lb://email-rest-service
          predicates:
            - Path=/emails
        - id: authorization-server
          uri: lb://authorization-server
          predicates:
#            - Path=/issuer/oauth2/token
            - Path=/issuer/forgot/changePassword, /issuer/forgot/emailUsername,
              /issuer/.well-known/openid-configuration,
              /issuer/login, /issuer/login?error #/issuer/**,
          #filters:
          #  - RewritePath=/issuer/(?<segment>.*), /$\{segment}
        - id: oauth2-token-mediator
          uri: lb://oauth2-token-mediator
          predicates:
            - Path=/oauth2-token-mediator/authorize,
                    /oauth2-token-mediator/token,
              /oauth2-token-mediator/pkce-authorize,
              /oauth2-token-mediator/public-pkce-token
        - id: organization-rest-service
          uri: lb://organization-rest-service
          predicates:
            - Path=/organizations,
                  /organizations/users,
                  /organizations/{organizationId},                   
                  /organizations/{organizationId}/users,
                  /organizations/{organizationId}/positions,
                  /organizations/{organizationId}/positions/{id},
        - id: role-rest-service
          uri: lb://role-rest-service
          predicates:
            - Path=/roles,
                  /roles/{id},
                  /roles/user,
                  /roles/organization/{organizationId},
                  /roles/clientId/{clientId}/users,
                  /roles/clientId/{clientId}/users/{userId},
                  /roles/{roleId}/users/{userId}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
          audiences: ${OAUTH_AUDIENCES}

logging:
  level:
    root: info
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    me:
      sonam: info

permitpath:
  - path: /
  - path: /favicon.ico
    httpMethods: GET
  - path: /actuator/health
  - path: /users
    httpMethods: POST
  - path: /users/**
    httpMethods: GET
  - path: /api/health/*
    httpMethods: GET
  - path: /cars
  - path: /cars/**
  - path: /accounts/activate/*/*
    httpMethods: GET
  - path: /accounts/api/health/*
  - path: /accounts/active/*/*
    httpMethods: GET
  - path: /accounts/emailactivationlink/*
    httpMethods: PUT
  - path: /accounts/emailmysecret/*
    httpMethods: PUT
#  - path: /accounts/*/*
#    httpMethods: POST
  - path: /accounts/email/authenticationId/*
  - path: /accounts/authentications/password
    httpMethods: PUT
  - path: /accounts/validate/secret/*/*
    httpMethods: PUT
  - path: /accounts/*/active/*
    httpMethods: GET
  - path: /authentications/authenticate
    httpMethods: POST
  - path: /actuator/gateway/routes/account-rest-service
    httpMethods: GET
  - path: /actuator/gateway/routes/authentication-rest-service
    httpMethods: GET
  - path: /actuator/gateway/routes/host_route
  - path: /issuer/oauth2/token
    httpMethods: POST
  - path: /issuer/.well-known/openid-configuration
    httpMethods: GET
  - path: /oauth2-token-mediator/authorize
    httpMethods: GET
  - path: /oauth2-token-mediator/token
    httpMethods: POST
  - path: /oauth2-token-mediator/pkce-authorize
    httpMethods: GET
  - path: /oauth2-token-mediator/public-pkce-token
    httpMethods: POST
  - path: /issuer/login
    httpMethods: GET, POST
  - path: /issuer/login?error
    httpMethods: GET, POST
  - path: /issuer/forgot/changePassword
    httpMethods: POST
  - path: /issuer/forgot/emailUsername
    httpMethods: POST

allowedOrigins: ${ALLOWED_ORIGINS}
originValue: ${ORIGIN_VALUE}
authorizationServer: ${AUTHORIZATION_SERVER}