server:
  port: 8080

eureka:
  instance:
    statusPageUrlPath: https://api-gateway.sonam.cloud/actuator
    healthCheckUrlPath: https://api-gateway.sonam.cloud/actuator/health
  client:
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://example.org
          predicates:
            - Path=/foo/{segment}
        - id: account-rest-service
          uri: lb://account-rest-service
          predicates:
            - Path=/accounts/validate/secret/{authenticationId}/{secret},
                    /accounts/email/authenticationId/{email},
                    /accounts/emailmysecret/{authenticationId},
                    /accounts/emailactivationlink/{authenticationId},
                    /accounts/authentications/password,
                    /accounts/activate/{authenticationId}/{secret}
        - id: authentication-rest-service
          uri: lb://authentication-rest-service
          predicates:
            - Path=/authentications/authenticate
        - id: user-rest-service
          uri: lb://user-rest-service
          predicates:
            - Path=/users
        - id: email-rest-service
          uri: lb://email-rest-service
          predicates:
            - Path=/emails
        - id: authorization-server
          uri: lb://authorization-server
          predicates:
#            - Path=/issuer/oauth2/token
            - Path=/issuer/**
          #filters:
          #  - RewritePath=/issuer/(?<segment>.*), /$\{segment}
        - id: oauth2-token-mediator
          uri: lb://oauth2-token-mediator
          predicates:
            - Path=/oauth2-token-mediator/authorize,
                    /oauth2-token-mediator/token

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL} #http://api-gateway/issuer


logging:
  level:
    root: info
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    me:
      sonam: info

permitpath:
  - path: /
  - path: /actuator/health
  - path: /users
    httpMethods: POST
  - path: /users/**
    httpMethods: GET
  - path: /api/health/*
    httpMethods: GET
  - path: /cars
  - path: /cars/**
  - path: /accounts/activate/*/*
    httpMethods: GET
  - path: /accounts/api/health/*
  - path: /accounts/active/*/*
    httpMethods: GET
  - path: /accounts/emailactivationlink/*
    httpMethods: PUT
  - path: /accounts/emailmysecret/*
    httpMethods: PUT
#  - path: /accounts/*/*
#    httpMethods: POST
  - path: /accounts/email/authenticationId/*
    httpMethods: PUT
  - path: /accounts/validate/secret/*/*
    httpMethods: PUT
  - path: /authentications/authenticate
    httpMethods: POST
  - path: /actuator/gateway/routes/account-rest-service
    httpMethods: GET
  - path: /actuator/gateway/routes/authentication-rest-service
    httpMethods: GET
  - path: /actuator/gateway/routes/host_route
  - path: /issuer/oauth2/token
    httpMethods: POST
  - path: /issuer/.well-known/openid-configuration
    httpMethods: GET
  - path: /oauth2-token-mediator/authorize
    httpMethods: GET
  - path: /oauth2-token-mediator/token
    httpMethods: POST

token:
  audiences: ${OAUTH_CLIENTS}
  issuerUri: ${ISSUER_URL} #http://api-gateway/issuer #this is used for accessing the issuer for jwt validation