EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

DEFAULT_ZONE: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

ISSUER_ADDRESS: http://api-gateway:9001 #9001 port is for local authoriation-server
ISSUER_URI: ${ISSUER_ADDRESS}/issuer
OAUTH_AUDIENCES: oauth-client
#JWT_SET_URI: ${ISSUER_ADDRESS}/issuer/.well-known/jwks.json #not needed

# eureka used in local deployment only, on k8 use application-kubernetes.yaml
eureka:
  instance:
    statusPageUrlPath: https://api-gateway.sonam.cloud/actuator
    healthCheckUrlPath: https://api-gateway.sonam.cloud/actuator/health
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE}

ALLOWED_ORIGINS: api-gateway, *, 127.0.0.1, 10.0.0.28
ORIGIN_VALUE: http://api-gateway
AUTHORIZATION_SERVER: api-gateway:9001