EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

eureka:
  client:
    enabled: true

DEFAULT_ZONE: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

ISSUER_URL: http://api-gateway:9001/issuer  #9001 port is for authoriation-server locally

OAUTH_CLIENTS: oauth-client

