EUREKA_HOST: localhost:8761
EUREKA_USER: test
EUREKA_PASSWORD: test

eureka:
  client:
    enabled: true

DEFAULT_ZONE: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOST}/eureka

# ISSUER_URL here is used for pulling the public certs from authorization-server for token validation
#ISSUER_URL:  http://10.0.0.28:9001
#ISSUER_URL: http://authorization-server:9001
#ISSUER_URL: http://my-server:9001
#ISSUER_URL: http://api-gateway:9001/issuer

#GATEWAY_ISSUER_ENDPOINT: http://api-gateway:9001/issuer  #this will be for spring-security-config

#ISSUER_ENDPOINT: http://api-gateway:9001/issuer   #this is for the jwt-decoder in token-filter

ISSUER_URL: http://api-gateway:9001/issuer

OAUTH_CLIENTS: oauth-client

