server:
  port: 8080

eureka:
  instance:
    statusPageUrlPath: https://api-gateway.sonam.cloud/actuator
    healthCheckUrlPath: https://api-gateway.sonam.cloud/actuator/health
  client:
    serviceUrl:
      defaultZone: ${DEFAULT_ZONE}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://example.org
          predicates:
            - Path=/foo/{segment}
        - id: account-rest-service
          uri: lb://account-rest-service
          predicates:
            - Path=/accounts/validate/secret/{authenticationId}/{secret},
                    /accounts/email/authenticationId/{email},
                    /accounts/emailmysecret/{authenticationId},
                    /accounts/emailactivationlink/{authenticationId},
                    /accounts/authentications/password,
                    /accounts/activate/{authenticationId}/{secret}
        - id: authentication-rest-service
          uri: lb://authentication-rest-service
          predicates:
            - Path=/authentications/authenticate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9001


logging:
  level:
    root: info
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    me:
      sonam: info

permitpath:
  - path: /
  - path: /actuator/health
  - path: /users
    httpMethods: POST
  - path: /users/**
    httpMethods: GET
  - path: /api/health/*
    httpMethods: GET
  - path: /cars
  - path: /cars/**
  - path: /accounts/activate/*/*
    httpMethods: GET
  - path: /accounts/api/health/*
  - path: /accounts/active/*/*
    httpMethods: GET
  - path: /accounts/emailactivationlink/*
    httpMethods: PUT
  - path: /accounts/emailmysecret/*
    httpMethods: PUT
#  - path: /accounts/*/*
#    httpMethods: POST
  - path: /accounts/email/authenticationId/*
    httpMethods: PUT
  - path: /accounts/validate/secret/*/*
    httpMethods: PUT
  - path: /authentications/authenticate
    httpMethods: POST
  - path: /actuator/gateway/routes/account-rest-service
    httpMethods: GET
  - path: /actuator/gateway/routes/authentication-rest-service
    httpMethods: GET
  - path: /actuator/gateway/routes/host_route


#okta:
#  oauth2:
#    issuer: https://dev-975443.okta.com/oauth2/default
#    client-secret: ${OKTA_CLIENT_SECRET}
#    client-id: 0oa971hyyjI3Dsk7d4x7

