server:
  port: 8080

eureka:
  instance:
    statusPageUrlPath: https://api-gateway.sonam.cloud/actuator
    healthCheckUrlPath: https://api-gateway.sonam.cloud/actuator/health
  client:
    serviceUrl:
      defaultZone: https://${EUREKA_USER}:${EUREKA_PASSWORD}@discovery-service.sonam.cloud/eureka

spring:
  application:
    name: api-gateway

logging:
  level:
    root: debug
    me:
      sonam: info

jwt-service:
  root: ${JWT_REST_SERVICE}
  public-key-id: /jwts/publickeys/{keyId}
  accesstoken: /jwts/accesstoken

permitpath:
  - path: /actuator
  - path: /actuator/health

#okta:
#  oauth2:
#    issuer: https://dev-975443.okta.com/oauth2/default
#    client-secret: ${OKTA_CLIENT_SECRET}
#    client-id: 0oa971hyyjI3Dsk7d4x7

